### PR TITLE
Extract out signing logic

### PR DESCRIPTION
**Pull request by meadsteve**
This is based off the branch in PR #2 so please ignore for the moment.

It pulls the request signing logic out of the http client so this can have a small test to make sure it's signing the correct things.

### CODE REVIEW

**Comment by edgurgel** [comment]
Could you rebase this branch with master so the PR will show just 1 commit? 

Thanks again for the contribution! :+1: 

I will release a new version soon.

**Comment by meadsteve** [comment]
@edgurgel no problem. I'll fix the empty lines and rebase this evening.

**Comment by meadsteve** [comment]
@edgurgel bit later than I planned but all sorted now!

**Comment by edgurgel** [comment]
Thanks! :tada:

**Pull request merged**
