### PR TITLE
Update the Signaturex dep

### PR DESCRIPTION
**Pull request by joshk**

### CODE REVIEW

**Comment by edgurgel** [comment]
Thank you! :+1:

**Comment by joshk** [comment]
Sweet! When do you plan to release a new version?

**Comment by edgurgel** [comment]
In 5 minutes! :)

**Comment by edgurgel** [comment]
https://hex.pm/packages/pusher/0.1.3 & https://github.com/edgurgel/pusher/releases/tag/v0.1.3

**Comment by joshk** [comment]
HUZZAH!

**Pull request merged**
